# Generated by Django 6.0.6 on 2026-06-16 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название сорта')),
                ('origin_country', models.CharField(max_length=50, verbose_name='Страна происхождения')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('altitude_min', models.PositiveIntegerField(help_text='Высота в метрах (минимум)', verbose_name='Мин. высота (м)')),
                ('altitude_max', models.PositiveIntegerField(help_text='Высота в метрах (максимум)', verbose_name='Макс. высота (м)')),
                ('process_method', models.CharField(choices=[('washed', 'Мытый (Washed)'), ('natural', 'Натуральный (Natural)'), ('honey', 'Мёд (Honey)')], max_length=20, verbose_name='Метод обработки')),
                ('acidity_score', models.FloatField(help_text='Оценка кислотности от 1 (низкая) до 10 (высокая)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Кислотность (1-10)')),
                ('density', models.FloatField(default=0.65, help_text='Плотность обжаренного зерна (г/см³)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.8)], verbose_name='Плотность зерна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сорт кофе',
                'verbose_name_plural': 'Сорта кофе',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrewRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Стандартный рецепт', max_length=100, verbose_name='Название рецепта')),
                ('water_temperature', models.FloatField(help_text='Температура воды в градусах Цельсия', validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)], verbose_name='Температура воды (°C)')),
                ('grind_size', models.CharField(choices=[('extra_fine', 'Очень мелкий (эспрессо 0.2-0.3 мм)'), ('fine', 'Мелкий (аэропресс 0.4-0.6 мм)'), ('medium_fine', 'Средне-мелкий (воронка 0.6-0.8 мм)'), ('medium', 'Средний (пуровер 0.8-1.0 мм)'), ('coarse', 'Крупный (френч-пресс 1.0-1.2 мм)')], max_length=20, verbose_name='Помол')),
                ('brew_time_seconds', models.PositiveIntegerField(default=180, help_text='Время контакта воды с кофе в секундах', verbose_name='Время заваривания (сек)')),
                ('coffee_dose', models.FloatField(default=15.0, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)], verbose_name='Доза кофе (г)')),
                ('water_volume', models.FloatField(default=250.0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)], verbose_name='Объём воды (мл)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый рецепт')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='brewlab.coffeebean', verbose_name='Сорт кофе')),
            ],
            options={
                'verbose_name': 'Рецепт заваривания',
                'verbose_name_plural': 'Рецепты заваривания',
                'ordering': ['coffee', '-created_at'],
                'unique_together': {('coffee', 'water_temperature', 'grind_size')},
            },
        ),
        migrations.CreateModel(
            name='TastePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acidity_intensity', models.FloatField(help_text='Интенсивность кислотности (0-100)', verbose_name='Кислинка')),
                ('sweetness_intensity', models.FloatField(help_text='Интенсивность сладости (0-100)', verbose_name='Сладость')),
                ('bitterness_intensity', models.FloatField(help_text='Интенсивность горечи (0-100)', verbose_name='Горечь')),
                ('balance_type', models.CharField(choices=[('acidic', '☕ Кислотный перекос (недожар/недоэкстракция)'), ('balanced', '⭐ Сбалансировано (идеально)'), ('bitter', '🔥 Горький перекос (пережар/переэкстракция)')], max_length=20, verbose_name='Тип баланса')),
                ('recommended_temperature_adjustment', models.IntegerField(help_text='Рекомендуемое изменение температуры в градусах', verbose_name='Корректировка температуры (°C)')),
                ('tds_estimate', models.FloatField(help_text='Total Dissolved Solids - процент растворённых веществ', verbose_name='TDS (%)')),
                ('extraction_yield', models.FloatField(default=18.0, help_text='Процент экстракции (извлечения) из зерна', verbose_name='Экстракция (%)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Время расчёта')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='brewlab.brewrecipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Прогноз вкуса',
                'verbose_name_plural': 'Прогнозы вкуса',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
